---
- name: Disable SSH password authentication
  hosts: all
  become: true

  tasks:
    - name: Disable PasswordAuthentication in 
      lineinfile:
        path: /etc/ssh/ssh_config
        regexp: '^\s*PasswordAuthentication\s*no'
        line: 'PasswordAuthentication no'
        state: present

    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
