- name: SUSE Updates
  hosts: all
  become: true

  gather_facts: false

  tasks:

    - name: Repos refresh
      ansible.builtin.command: zypper --non-interactive refresh
      changed_when: false

    - name: System update
      ansible.builtin.zypper:
        name: "*"
        state: latest
        update_cache: yes

    - name: Check reboot flag
      ansible.builtin.stat:
        path: /run/reboot-needed
      register: reboot_file

    - name: Reboot if needed
      ansible.builtin.reboot:
        msg: "Reboot after updates"
        reboot_timeout: 900
      when: reboot_file.stat.exists
